# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'biddialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import infodialog

class Ui_Biddialog(object):
    def setupUi(self, Biddialog,client):
        Biddialog.setObjectName("Biddialog")
        Biddialog.resize(400, 300)
        self.bid_GB = QtWidgets.QGroupBox(Biddialog)
        self.bid_GB.setGeometry(QtCore.QRect(20, 60, 321, 171))
        self.bid_GB.setObjectName("bid_GB")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.bid_GB)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(40, 40, 251, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.input_price_hl = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.input_price_hl.setContentsMargins(0, 0, 0, 0)
        self.input_price_hl.setObjectName("input_price_hl")
        self.bid_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.bid_label.setStyleSheet("QPushButton{\n"
"background-color: rgb(179, 214, 230);\n"
"color: white;\n"
"border:2px solid #000000;\n"
"padding: 16px 32px;\n"
"text-align: center;\n"
"font-size: 16px;\n"
"margin:4px 2px;\n"
"border-radius: 12px;\n"
"hover{color: black};\n"
"hover{background-color: white};\n"
"hover{border: 2px solid #000000}\n"
"}")
        self.bid_label.setObjectName("bid_label")
        self.input_price_hl.addWidget(self.bid_label)
        self.bid_text = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.bid_text.setToolTip("")
        self.bid_text.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.bid_text.setInputMask("")
        self.bid_text.setText("")
        self.bid_text.setMaxLength(100000)
        self.bid_text.setObjectName("bid_text")
        self.input_price_hl.addWidget(self.bid_text)
        self.bidokbutton = QtWidgets.QDialogButtonBox(self.bid_GB)
        self.bidokbutton.setGeometry(QtCore.QRect(-70, 110, 341, 32))
        self.bidokbutton.setOrientation(QtCore.Qt.Horizontal)
        self.bidokbutton.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.bidokbutton.setCenterButtons(False)
        self.bidokbutton.setObjectName("bidokbutton")

        self.retranslateUi(Biddialog)
        self.bidokbutton.accepted.connect(Biddialog.accept)
        self.bidokbutton.rejected.connect(Biddialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Biddialog)

        # 按钮绑定
        self.bidokbutton.accepted.connect(lambda: self.bid(client))

    def retranslateUi(self, Biddialog):
        _translate = QtCore.QCoreApplication.translate
        Biddialog.setWindowTitle(_translate("Biddialog", "Dialog"))
        self.bid_GB.setTitle(_translate("Biddialog", "竞价"))
        self.bid_label.setText(_translate("Biddialog", "输入价格      "))
        self.bid_text.setWhatsThis(_translate("Biddialog", "id"))
        self.bid_text.setPlaceholderText(_translate("Biddialog", "请输入价格..."))

    def bid(self,client):
        # 竞价
        price = int(self.bid_text.text())  # 取得客户输入的价格
        client.bid(price)
