# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'infodialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_infodialog(object):
    def setupUi(self, infodialog):
        infodialog.setObjectName("infodialog")
        infodialog.resize(440, 265)
        self.infookbutton = QtWidgets.QDialogButtonBox(infodialog)
        self.infookbutton.setGeometry(QtCore.QRect(70, 200, 341, 32))
        self.infookbutton.setOrientation(QtCore.Qt.Horizontal)
        self.infookbutton.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.infookbutton.setObjectName("infookbutton")
        self.infolabe = QtWidgets.QLabel(infodialog)
        self.infolabe.setGeometry(QtCore.QRect(70, 70, 311, 91))
        self.infolabe.setObjectName("infolabe")

        self.retranslateUi(infodialog)
        self.infookbutton.accepted.connect(infodialog.accept)
        self.infookbutton.rejected.connect(infodialog.reject)
        QtCore.QMetaObject.connectSlotsByName(infodialog)

    def retranslateUi(self, infodialog):
        _translate = QtCore.QCoreApplication.translate
        infodialog.setWindowTitle(_translate("infodialog", "Dialog"))
        self.infolabe.setText(_translate("infodialog", "content"))
