# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'signinwidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import client_message

class Ui_Form(client_message.Client):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.signin_groupbox = QtWidgets.QGroupBox(Form)
        self.signin_groupbox.setGeometry(QtCore.QRect(20, 50, 341, 171))
        self.signin_groupbox.setObjectName("signin_groupbox")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.signin_groupbox)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(50, 30, 241, 31))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.usernamehl = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.usernamehl.setContentsMargins(0, 0, 0, 0)
        self.usernamehl.setObjectName("usernamehl")
        self.name_label = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.name_label.setStyleSheet("QPushButton{\n"
"background-color: rgb(179, 214, 230);\n"
"color: white;\n"
"border:2px solid #000000;\n"
"padding: 16px 32px;\n"
"text-align: center;\n"
"font-size: 16px;\n"
"margin:4px 2px;\n"
"border-radius: 12px;\n"
"hover{color: black};\n"
"hover{background-color: white};\n"
"hover{border: 2px solid #000000}\n"
"}")
        self.name_label.setObjectName("name_label")
        self.usernamehl.addWidget(self.name_label)
        self.name_text = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.name_text.setToolTip("")
        self.name_text.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.name_text.setInputMask("")
        self.name_text.setText("")
        self.name_text.setMaxLength(100000)
        self.name_text.setObjectName("name_text")
        self.usernamehl.addWidget(self.name_text)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.signin_groupbox)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(50, 60, 241, 31))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.userkeyhl = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.userkeyhl.setContentsMargins(0, 0, 0, 0)
        self.userkeyhl.setObjectName("userkeyhl")
        self.key_label = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.key_label.setObjectName("key_label")
        self.userkeyhl.addWidget(self.key_label)
        self.key_text = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.key_text.setObjectName("key_text")
        self.userkeyhl.addWidget(self.key_text)
        self.siginbuttons = QtWidgets.QDialogButtonBox(self.signin_groupbox)
        self.siginbuttons.setGeometry(QtCore.QRect(90, 110, 156, 23))
        self.siginbuttons.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.siginbuttons.setObjectName("siginbuttons")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        self.siginbuttons.clicked.connect(Form.accept)
        self.siginbuttons.clicked.connect(Form.reject)
        self.siginbuttons.clicked.connect(self.signin_button_handler)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.signin_groupbox.setTitle(_translate("Form", "注册"))
        self.name_label.setText(_translate("Form", "用户名  "))
        self.name_text.setWhatsThis(_translate("Form", "id"))
        self.name_text.setPlaceholderText(_translate("Form", "请输入用户名..."))
        self.key_label.setText(_translate("Form", "用户密码"))
        self.key_text.setPlaceholderText(_translate("Form", "请输入密码..."))


    def signin_button_handler(self):
        name = self.name_text.text()
        key = self.key_text.text()
        self.signin(name, key)  # 发送注册消息给server

        s = self.recv()  # 接受server消息
        QtWidgets.QMessageBox.about(self,'注册成功！',s)
