# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'signindialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import client_message
import infodialog

class Ui_SigninDialog(client_message.Client):  # 继承该类
    def setupUi(self, SigninDialog):
        SigninDialog.setObjectName("SigninDialog")
        SigninDialog.resize(400, 300)
        self.signin_groupbox = QtWidgets.QGroupBox(SigninDialog)
        self.signin_groupbox.setGeometry(QtCore.QRect(20, 50, 341, 171))
        self.signin_groupbox.setObjectName("signin_groupbox")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.signin_groupbox)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(50, 30, 241, 31))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.usernamehl = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.usernamehl.setContentsMargins(0, 0, 0, 0)
        self.usernamehl.setObjectName("usernamehl")
        self.name_label = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.name_label.setStyleSheet("QPushButton{\n"
"background-color: rgb(179, 214, 230);\n"
"color: white;\n"
"border:2px solid #000000;\n"
"padding: 16px 32px;\n"
"text-align: center;\n"
"font-size: 16px;\n"
"margin:4px 2px;\n"
"border-radius: 12px;\n"
"hover{color: black};\n"
"hover{background-color: white};\n"
"hover{border: 2px solid #000000}\n"
"}")
        self.name_label.setObjectName("name_label")
        self.usernamehl.addWidget(self.name_label)
        self.name_text = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.name_text.setToolTip("")
        self.name_text.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.name_text.setInputMask("")
        self.name_text.setText("")
        self.name_text.setMaxLength(100000)
        self.name_text.setObjectName("name_text")
        self.usernamehl.addWidget(self.name_text)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.signin_groupbox)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(50, 60, 241, 31))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.userkeyhl = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.userkeyhl.setContentsMargins(0, 0, 0, 0)
        self.userkeyhl.setObjectName("userkeyhl")
        self.key_label = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.key_label.setObjectName("key_label")
        self.userkeyhl.addWidget(self.key_label)
        self.key_text = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.key_text.setObjectName("key_text")
        self.userkeyhl.addWidget(self.key_text)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.signin_groupbox)
        self.buttonBox.setGeometry(QtCore.QRect(90, 110, 155, 23))
        self.buttonBox.setFocusPolicy(QtCore.Qt.NoFocus)
        self.buttonBox.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")

        self.retranslateUi(SigninDialog)
        QtCore.QMetaObject.connectSlotsByName(SigninDialog)
        self.buttonBox.accepted.connect(SigninDialog.accept)
        self.buttonBox.rejected.connect(SigninDialog.reject)
        self.buttonBox.accepted.connect(self.signin_button_handler)

    def retranslateUi(self, SigninDialog):
        _translate = QtCore.QCoreApplication.translate
        SigninDialog.setWindowTitle(_translate("SigninDialog", "Dialog"))
        self.signin_groupbox.setTitle(_translate("SigninDialog", "注册"))
        self.name_label.setText(_translate("SigninDialog", "用户名  "))
        self.name_text.setWhatsThis(_translate("SigninDialog", "id"))
        self.name_text.setPlaceholderText(_translate("SigninDialog", "请输入用户名..."))
        self.key_label.setText(_translate("SigninDialog", "用户密码"))
        self.key_text.setPlaceholderText(_translate("SigninDialog", "请输入密码..."))

    def signin_button_handler(self):
        name = self.name_text.text()
        key = self.key_text.text()
        self.signin(name, key)  # 发送注册消息给server

        s = self.recv()  # 接受server消息
        # 实例化消息窗口 提示id
        info_dialog = QtWidgets.QDialog()
        ui_info_dialog = infodialog.Ui_infodialog()
        ui_info_dialog.setupUi(info_dialog)
        ui_info_dialog.infolabe.setText(s)
        info_dialog.exec_()





