# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets
import sys
from client_ui import biddialog


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(967, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.upperline = QtWidgets.QFrame(self.centralwidget)
        self.upperline.setGeometry(QtCore.QRect(0, 0, 970, 25))
        self.upperline.setStyleSheet("background-color : rgb(32, 106, 122);")
        self.upperline.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.upperline.setFrameShadow(QtWidgets.QFrame.Raised)
        self.upperline.setObjectName("upperline")
        self.FDU_label = QtWidgets.QLabel(self.upperline)
        self.FDU_label.setGeometry(QtCore.QRect(10, 0, 281, 21))
        self.FDU_label.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 11pt \"黑体\";")
        self.FDU_label.setObjectName("FDU_label")
        self.announcementbox = QtWidgets.QGroupBox(self.centralwidget)
        self.announcementbox.setGeometry(QtCore.QRect(40, 120, 351, 311))
        self.announcementbox.setObjectName("announcementbox")
        self.anouncementscrollarea_2 = QtWidgets.QScrollArea(self.announcementbox)
        self.anouncementscrollarea_2.setGeometry(QtCore.QRect(9, 29, 331, 271))
        self.anouncementscrollarea_2.setWidgetResizable(True)
        self.anouncementscrollarea_2.setObjectName("anouncementscrollarea_2")
        self.anouncementscrollarea = QtWidgets.QWidget()
        self.anouncementscrollarea.setGeometry(QtCore.QRect(0, 0, 329, 269))
        self.anouncementscrollarea.setObjectName("anouncementscrollarea")
        self.announcementtext = QtWidgets.QTextBrowser(self.anouncementscrollarea)
        self.announcementtext.setGeometry(QtCore.QRect(0, 0, 331, 271))
        self.announcementtext.setObjectName("announcementtext")
        self.anouncementscrollarea_2.setWidget(self.anouncementscrollarea)
        self.OperationButtonbox = QtWidgets.QGroupBox(self.centralwidget)
        self.OperationButtonbox.setGeometry(QtCore.QRect(540, 130, 351, 291))
        self.OperationButtonbox.setObjectName("OperationButtonbox")
        self.gridLayoutWidget = QtWidgets.QWidget(self.OperationButtonbox)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(30, 40, 291, 221))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.bidbutton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.bidbutton.setObjectName("bidbutton")
        self.gridLayout.addWidget(self.bidbutton, 0, 0, 1, 1)
        self.refreshbutton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.refreshbutton.setObjectName("refreshbutton")
        self.gridLayout.addWidget(self.refreshbutton, 1, 0, 1, 1)
        self.leavebutton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.leavebutton.setObjectName("leavebutton")
        self.gridLayout.addWidget(self.leavebutton, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 967, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.FDU_label.setText(_translate("MainWindow", "FDU 定制电动车牌拍卖"))
        self.announcementbox.setTitle(_translate("MainWindow", "公开信息"))
        self.announcementtext.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">这里是公开信息。</p></body></html>"))
        self.OperationButtonbox.setTitle(_translate("MainWindow", "参与竞标"))
        self.bidbutton.setText(_translate("MainWindow", "竞价(>o<)"))
        self.refreshbutton.setText(_translate("MainWindow", "刷新:)"))
        self.leavebutton.setText(_translate("MainWindow", "离开:("))


        # 绑定槽函数
    # 竞价按钮处理函数
    def bid_button_handler(self):
        bid_dialog = biddialog.Ui_Dialog()


if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    # 实例化主窗口
    mainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(mainWindow)
    # 实例化子窗口
    bid_dialog = QtWidgets.QDialog()
    bid_dialog_ui = biddialog.Ui_Dialog()
    bid_dialog_ui.setupUi(bid_dialog)

    # 按钮绑定事件
    bid_button = ui.bidbutton
    bid_button.clicked.connect(bid_dialog.show)

    mainWindow.show()
    sys.exit(app.exec_())
