# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'kickdialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import server_message

class Ui_Dialog(object):
    def setupUi(self, Dialog,server):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 200)
        self.kick_button = QtWidgets.QDialogButtonBox(Dialog)
        self.kick_button.setGeometry(QtCore.QRect(30, 150, 341, 32))
        self.kick_button.setOrientation(QtCore.Qt.Horizontal)
        self.kick_button.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.kick_button.setObjectName("kick_button")
        self.open_groupbox = QtWidgets.QGroupBox(Dialog)
        self.open_groupbox.setGeometry(QtCore.QRect(30, 20, 341, 111))
        self.open_groupbox.setObjectName("open_groupbox")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.open_groupbox)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(60, 40, 241, 31))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.usernamehl = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.usernamehl.setContentsMargins(0, 0, 0, 0)
        self.usernamehl.setObjectName("usernamehl")
        self.kick_id_label = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.kick_id_label.setStyleSheet("QPushButton{\n"
"background-color: rgb(179, 214, 230);\n"
"color: white;\n"
"border:2px solid #000000;\n"
"padding: 16px 32px;\n"
"text-align: center;\n"
"font-size: 16px;\n"
"margin:4px 2px;\n"
"border-radius: 12px;\n"
"hover{color: black};\n"
"hover{background-color: white};\n"
"hover{border: 2px solid #000000}\n"
"}")
        self.kick_id_label.setObjectName("kick_id_label")
        self.usernamehl.addWidget(self.kick_id_label)
        self.num_text = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.num_text.setToolTip("")
        self.num_text.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.num_text.setInputMask("")
        self.num_text.setText("")
        self.num_text.setMaxLength(100000)
        self.num_text.setObjectName("num_text")
        self.usernamehl.addWidget(self.num_text)

        self.retranslateUi(Dialog)
        self.kick_button.accepted.connect(Dialog.accept)
        self.kick_button.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        # 绑定事件
        self.kick_button.accepted.connect(lambda:self.kick_ok_handler(server))

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.open_groupbox.setTitle(_translate("Dialog", "踢人"))
        self.kick_id_label.setText(_translate("Dialog", "待踢人id"))
        self.num_text.setWhatsThis(_translate("Dialog", "id"))
        self.num_text.setPlaceholderText(_translate("Dialog", "请输入待踢人id..."))

    def kick_ok_handler(self,server):
        id = int(self.num_text.text())
        server.kick_out(bidderID = id)